[package]
name = "msrtc-rans"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Safe public Rust entropy-coder API for msrtc_rans"
documentation = "https://docs.rs/msrtc-rans"

[features]
default = []
std = []

[dependencies]
msrtc-rans-core = { path = "../msrtc-rans-core", version = "0.2" }

[lints]
rust.unsafe_code = "forbid"
